### ISSUE TITLE
Twitch irc

### ISSUE THREAD

**Issue by arcanewater** [cshivers/IrcClient-csharp#4]
Hey is it possible to use it with Twitch irc? Also how you login i saw there is client.ServerPassword but no password? Does serverPassword counts as user password?

**Comment by cshivers** [comment]
I've used a modified version of this code before to work with Twitch, but this code does not have all of the code required to work by default. When I find time, I'll look into adding this functionality.

**Comment by SeeingBlue** [comment]
Check out my fork. I modified this to work with Twitch features. It's what I use for Ultimate Twitch Bot.
https://github.com/SeeingBlue/IrcClient-csharp

**Comment by SeeingBlue** [comment]
And yes, OAuth is sent as .ServerPass

**Comment by seanmitch** [comment]
Can we close this out?
